baseUrl = "https://mirrors.ctan.org/fonts/newcomputermodern/otf/"

# Name, Family Name, Styles, Weight, Name for Humans, PFM Family, Italic angle override, Os2 Stylemap
specification = [
#["NewCM08-Book","New Computer Modern 08","Book","Book","New Computer Modern 08 Book","Serif","-91","64"],
#["NewCM08-BookItalic","New Computer Modern 08","Book Italic","Book","New Computer Modern 08 Book Italic","Serif","-91","1"],
#["NewCM08-Italic","New Computer Modern 08","Italic","Regular","New Computer Modern 08 Italic","Serif","-91","1"],
#["NewCM08-Regular","New Computer Modern 08","Regular","Regular","New Computer Modern 08 Regular","Serif","-91","64"],
#["NewCM08Devanagari-Book","New Computer Modern 08 Devangari","Book","Book","New Computer Modern 08 Devangari Book","Serif","-91","64"],
#["NewCM08Devanagari-Regular","New Computer Modern 08 Devangari","Regular","Regular","New Computer Modern 08 Devangari Regular","Serif","-91","64"],
["NewCM10-Bold","New Computer Modern 10","Bold","Bold","New Computer Modern 10 Bold","Serif","-91","32"],
["NewCM10-BoldItalic","New Computer Modern 10","Bold Italic","Bold","New Computer Modern 10 Bold Italic","Serif","-91","33"],
["NewCM10-Book","New Computer Modern 10","Book","Book","New Computer Modern 10 Book","Serif","-91","64"],
["NewCM10-BookItalic","New Computer Modern 10","Book Italic","Book","New Computer Modern 10 Book Italic","Serif","-91","1"],
#["NewCM10-Italic","New Computer Modern 10","Italic","Regular","New Computer Modern 10 Italic","Serif","-91","1"],
#["NewCM10-Regular","New Computer Modern 10","Regular","Regular","New Computer Modern 10 Regular","Serif","-91","64"],
#["NewCM10Devanagari-Bold","New Computer Modern 10 Devangari","Bold","Bold","New Computer Modern 10 Devangari Bold","Serif","-91","32"],
#["NewCM10Devanagari-Book","New Computer Modern 10 Devangari","Book","Book","New Computer Modern 10 Devangari Book","Serif","-91","64"],
#["NewCM10Devanagari-Regular","New Computer Modern 10 Devangari","Regular","Regular","New Computer Modern 10 Devangari Regular","Serif","-91","64"],
["NewCMMath-Bold","New Computer Modern Math","Bold","Bold","New Computer Modern Math Bold","Serif","-91","32"],
["NewCMMath-Book","New Computer Modern Math","Book","Book","New Computer Modern Math Book","Serif","-91","64"],
#["NewCMMath-Regular","New Computer Modern Math","Regular","Regular","New Computer Modern Math Regular","Serif","-91","64"],
["NewCMMono10-Bold","New Computer Modern Mono 10","Bold","Bold","New Computer Modern Mono 10 Bold","Monoscape","-91","32"],
["NewCMMono10-BoldOblique","New Computer Modern Mono 10","Bold Oblique","Bold","New Computer Modern Mono 10 Bold Oblique","Monoscape","-12","33"],
["NewCMMono10-Book","New Computer Modern Mono 10","Book","Book","New Computer Modern Mono 10 Book","Monoscape","-91","64"],
["NewCMMono10-BookItalic","New Computer Modern Mono 10","Book Italic","Book","New Computer Modern Mono 10 Book Italic","Monoscape","-91","1"],
#["NewCMMono10-Italic","New Computer Modern Mono 10","Italic","Regular","New Computer Modern Mono 10 Italic","Monoscape","-91","1"],
#["NewCMMono10-Regular","New Computer Modern Mono 10","Regular","Regular","New Computer Modern Mono 10 Regular","Monoscape","-91","64"],
#["NewCMSans08-Book","New Computer Modern Sans 08","Book","Book","New Computer Modern Sans 08 Book","Sans","-91","64"],
#["NewCMSans08-BookOblique","New Computer Modern Sans 08","Book Oblique","Book","New Computer Modern Sans 08 Book Oblique","Sans","-12","1"],
#["NewCMSans08-Oblique","New Computer Modern Sans 08","Oblique","Regular","New Computer Modern Sans 08 Oblique","Sans","-12","1"],
#["NewCMSans08-Regular","New Computer Modern Sans 08","Regular","Regular","New Computer Modern Sans 08 Regular","Sans","-91","64"],
["NewCMSans10-Bold","New Computer Modern Sans 10","Bold","Bold","New Computer Modern Sans 10 Bold","Sans","-91","32"],
["NewCMSans10-BoldOblique","New Computer Modern Sans 10","Bold Oblique","Bold","New Computer Modern Sans 10 Bold Oblique","Sans","-12","33"],
["NewCMSans10-Book","New Computer Modern Sans 10","Book","Book","New Computer Modern Sans 10 Book","Sans","-91","64"],
["NewCMSans10-BookOblique","New Computer Modern Sans 10","Book Oblique","Book","New Computer Modern Sans 10 Book Oblique","Sans","-12","1"],
#["NewCMSans10-Oblique","New Computer Modern Sans 10","Oblique","Regular","New Computer Modern Sans 10 Oblique","Sans","-12","1"],
#["NewCMSans10-Regular","New Computer Modern Sans 10","Regular","Regular","New Computer Modern Sans 10 Regular","Sans","-91","64"],
["NewCMSansMath-Regular","New Computer Modern Sans Math","Regular","Regular","New Computer Modern Sans Math Regular","Sans","-91","64"],
#["NewCMUncial08-Bold","New Computer Modern Uncial 08","Bold","Bold","New Computer Modern Uncial 08 Bold","Decorative","-91","32"],
#["NewCMUncial08-Book","New Computer Modern Uncial 08","Book","Book","New Computer Modern Uncial 08 Book","Decorative","-91","64"],
#["NewCMUncial08-Regular","New Computer Modern Uncial 08","Regular","Regular","New Computer Modern Uncial 08 Regular","Decorative","-91","64"],
["NewCMUncial10-Bold","New Computer Modern Uncial 10","Bold","Bold","New Computer Modern Uncial 10 Bold","Decorative","-91","32"],
["NewCMUncial10-Book","New Computer Modern Uncial 10","Book","Book","New Computer Modern Uncial 10 Book","Decorative","-91","64"],
#["NewCMUncial10-Regular","New Computer Modern Uncial 10","Regular","Regular","New Computer Modern Uncial 10 Regular","Decorative","-91","64"]
];
